// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package dev.dbatrainer.ffi

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap
import android.os.Build
import androidx.annotation.RequiresApi
import java.util.concurrent.atomic.AtomicBoolean

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.ffi_dba_trainer_mobile_ffi_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.ffi_dba_trainer_mobile_ffi_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len)?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}

// Converter for `&[u8]` / `[ByRef] bytes` arguments.
//
// Only `lower` is valid — zero-copy byte buffers only flow foreign -> Rust,
// and only in argument position. `lift`, `read`, `write`, and
// `allocationSize` have no sound implementation here and all panic at
// runtime. The `FfiConverter` interface is implemented so that the
// compiler enforces the full method set (rather than relying on eyeball).
//
// The provided `ByteBuffer` MUST be direct — only direct buffers have a
// stable native address that JNA can expose via `getDirectBufferPointer`.
// The returned `ForeignBytes.ByValue` is only valid for the duration of
// the FFI call; the Rust side treats it as a borrow.
internal object FfiConverterByRefBytes : FfiConverter<java.nio.ByteBuffer, ForeignBytes.ByValue> {
    override fun lower(value: java.nio.ByteBuffer): ForeignBytes.ByValue {
        require(value.isDirect) { "UniFFI zero-copy &[u8] requires a direct ByteBuffer. Use ByteBuffer.allocateDirect()." }
        val remaining = value.remaining()
        val fb = ForeignBytes.ByValue()
        fb.len = remaining
        // Zero-length direct buffers: skip getDirectBufferPointer (platform-variable behavior)
        // and pass null. The Rust side treats (null, 0) as &[].
        fb.data = if (remaining == 0) null else com.sun.jna.Native.getDirectBufferPointer(value)
        return fb
    }

    override fun lift(value: ForeignBytes.ByValue): java.nio.ByteBuffer =
        error("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")

    override fun read(buf: java.nio.ByteBuffer): java.nio.ByteBuffer =
        error("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")

    override fun write(value: java.nio.ByteBuffer, buf: java.nio.ByteBuffer): Unit =
        error("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")

    override fun allocationSize(value: java.nio.ByteBuffer): ULong =
        error("ByRef bytes have no RustBuffer allocation size: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        val err = try { e.stackTraceToString() } catch(_: Throwable) { "" }
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(err)
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            val err = try { e.stackTraceToString() } catch(_: Throwable) { "" }
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(err)
        }
    }
}
// Initial value and increment amount for handles. 
// These ensure that Kotlin-generated handles always have the lowest bit set
private const val UNIFFI_HANDLEMAP_INITIAL = 1.toLong()
private const val UNIFFI_HANDLEMAP_DELTA = 2.toLong()

// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    // Start 
    private val counter = java.util.concurrent.atomic.AtomicLong(UNIFFI_HANDLEMAP_INITIAL)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(UNIFFI_HANDLEMAP_DELTA)
        map.put(handle, obj)
        return handle
    }

    // Clone a handle, creating a new one
    fun clone(handle: Long): Long {
        val obj = map.get(handle) ?: throw InternalException("UniffiHandleMap.clone: Invalid handle")
        return insert(obj)
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "dba_trainer_mobile_ffi"
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureDroppedCallback : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceClone : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
    : Long
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFutureDroppedCallbackStruct(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureDroppedCallback? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureDroppedCallback? = null,
    ): UniffiForeignFutureDroppedCallbackStruct(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureDroppedCallbackStruct) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureResultRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureResultVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureResultVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureResultVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureResultVoid.UniffiByValue,)
}

// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.

// For large crates we prevent `MethodTooLargeException` (see #2340)
// N.B. the name of the extension is very misleading, since it is
// rather `InterfaceTooLargeException`, caused by too many methods
// in the interface for large crates.
//
// By splitting the otherwise huge interface into two parts
// * UniffiLib (this)
// * IntegrityCheckingUniffiLib
// And all checksum methods are put into `IntegrityCheckingUniffiLib`
// we allow for ~2x as many methods in the UniffiLib interface.
//
// Note: above all written when we used JNA's `loadIndirect` etc.
// We now use JNA's "direct mapping" - unclear if same considerations apply exactly.
internal object IntegrityCheckingUniffiLib {
    init {
        Native.register(IntegrityCheckingUniffiLib::class.java, findLibraryName(componentName = "dba_trainer_mobile_ffi"))
        uniffiCheckContractApiVersion(this)
        uniffiCheckApiChecksums(this)
    }

    internal fun ensureInitialized() = Unit
    external fun uniffi_dba_trainer_mobile_ffi_checksum_func_core_version(
    ): Int
    external fun uniffi_dba_trainer_mobile_ffi_checksum_func_hello_android(
    ): Int
    external fun uniffi_dba_trainer_mobile_ffi_checksum_method_mobiletrainer_active_session(
    ): Int
    external fun uniffi_dba_trainer_mobile_ffi_checksum_method_mobiletrainer_cancel_session(
    ): Int
    external fun uniffi_dba_trainer_mobile_ffi_checksum_method_mobiletrainer_clear_statistics(
    ): Int
    external fun uniffi_dba_trainer_mobile_ffi_checksum_method_mobiletrainer_current_question(
    ): Int
    external fun uniffi_dba_trainer_mobile_ffi_checksum_method_mobiletrainer_start_all_topics_session(
    ): Int
    external fun uniffi_dba_trainer_mobile_ffi_checksum_method_mobiletrainer_start_course_session(
    ): Int
    external fun uniffi_dba_trainer_mobile_ffi_checksum_method_mobiletrainer_start_topic_session(
    ): Int
    external fun uniffi_dba_trainer_mobile_ffi_checksum_method_mobiletrainer_statistics_all(
    ): Int
    external fun uniffi_dba_trainer_mobile_ffi_checksum_method_mobiletrainer_statistics_course(
    ): Int
    external fun uniffi_dba_trainer_mobile_ffi_checksum_method_mobiletrainer_statistics_topic(
    ): Int
    external fun uniffi_dba_trainer_mobile_ffi_checksum_method_mobiletrainer_submit_answer(
    ): Int
    external fun uniffi_dba_trainer_mobile_ffi_checksum_method_mobiletrainer_topics(
    ): Int
    external fun uniffi_dba_trainer_mobile_ffi_checksum_constructor_mobiletrainer_new(
    ): Int
    external fun ffi_dba_trainer_mobile_ffi_uniffi_contract_version(
    ): Int

        
}

internal object UniffiLib {
    
    // The Cleaner for the whole library
    internal val CLEANER: UniffiCleaner by lazy {
        UniffiCleaner.create()
    }
    

    init {
        Native.register(UniffiLib::class.java, findLibraryName(componentName = "dba_trainer_mobile_ffi"))
        
    }

    internal fun ensureInitialized() = Unit
    external fun uniffi_dba_trainer_mobile_ffi_fn_clone_mobiletrainer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun uniffi_dba_trainer_mobile_ffi_fn_free_mobiletrainer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_dba_trainer_mobile_ffi_fn_constructor_mobiletrainer_new(`databasePath`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun uniffi_dba_trainer_mobile_ffi_fn_method_mobiletrainer_active_session(`ptr`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_dba_trainer_mobile_ffi_fn_method_mobiletrainer_cancel_session(`ptr`: Long,`sessionId`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_dba_trainer_mobile_ffi_fn_method_mobiletrainer_clear_statistics(`ptr`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun uniffi_dba_trainer_mobile_ffi_fn_method_mobiletrainer_current_question(`ptr`: Long,`sessionId`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_dba_trainer_mobile_ffi_fn_method_mobiletrainer_start_all_topics_session(`ptr`: Long,`limit`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_dba_trainer_mobile_ffi_fn_method_mobiletrainer_start_course_session(`ptr`: Long,`courseCode`: RustBuffer.ByValue,`limit`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_dba_trainer_mobile_ffi_fn_method_mobiletrainer_start_topic_session(`ptr`: Long,`topicId`: Long,`limit`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_dba_trainer_mobile_ffi_fn_method_mobiletrainer_statistics_all(`ptr`: Long,`limit`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_dba_trainer_mobile_ffi_fn_method_mobiletrainer_statistics_course(`ptr`: Long,`courseCode`: RustBuffer.ByValue,`limit`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_dba_trainer_mobile_ffi_fn_method_mobiletrainer_statistics_topic(`ptr`: Long,`topicId`: Long,`limit`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_dba_trainer_mobile_ffi_fn_method_mobiletrainer_submit_answer(`ptr`: Long,`sessionId`: Long,`questionId`: Long,`answerOptionIds`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_dba_trainer_mobile_ffi_fn_method_mobiletrainer_topics(`ptr`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_dba_trainer_mobile_ffi_fn_func_core_version(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun uniffi_dba_trainer_mobile_ffi_fn_func_hello_android(uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_dba_trainer_mobile_ffi_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_dba_trainer_mobile_ffi_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_dba_trainer_mobile_ffi_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit
    external fun ffi_dba_trainer_mobile_ffi_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_dba_trainer_mobile_ffi_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_dba_trainer_mobile_ffi_rust_future_cancel_u8(`handle`: Long,
    ): Unit
    external fun ffi_dba_trainer_mobile_ffi_rust_future_free_u8(`handle`: Long,
    ): Unit
    external fun ffi_dba_trainer_mobile_ffi_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_dba_trainer_mobile_ffi_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_dba_trainer_mobile_ffi_rust_future_cancel_i8(`handle`: Long,
    ): Unit
    external fun ffi_dba_trainer_mobile_ffi_rust_future_free_i8(`handle`: Long,
    ): Unit
    external fun ffi_dba_trainer_mobile_ffi_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Byte
    external fun ffi_dba_trainer_mobile_ffi_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_dba_trainer_mobile_ffi_rust_future_cancel_u16(`handle`: Long,
    ): Unit
    external fun ffi_dba_trainer_mobile_ffi_rust_future_free_u16(`handle`: Long,
    ): Unit
    external fun ffi_dba_trainer_mobile_ffi_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_dba_trainer_mobile_ffi_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_dba_trainer_mobile_ffi_rust_future_cancel_i16(`handle`: Long,
    ): Unit
    external fun ffi_dba_trainer_mobile_ffi_rust_future_free_i16(`handle`: Long,
    ): Unit
    external fun ffi_dba_trainer_mobile_ffi_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Short
    external fun ffi_dba_trainer_mobile_ffi_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_dba_trainer_mobile_ffi_rust_future_cancel_u32(`handle`: Long,
    ): Unit
    external fun ffi_dba_trainer_mobile_ffi_rust_future_free_u32(`handle`: Long,
    ): Unit
    external fun ffi_dba_trainer_mobile_ffi_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_dba_trainer_mobile_ffi_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_dba_trainer_mobile_ffi_rust_future_cancel_i32(`handle`: Long,
    ): Unit
    external fun ffi_dba_trainer_mobile_ffi_rust_future_free_i32(`handle`: Long,
    ): Unit
    external fun ffi_dba_trainer_mobile_ffi_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Int
    external fun ffi_dba_trainer_mobile_ffi_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_dba_trainer_mobile_ffi_rust_future_cancel_u64(`handle`: Long,
    ): Unit
    external fun ffi_dba_trainer_mobile_ffi_rust_future_free_u64(`handle`: Long,
    ): Unit
    external fun ffi_dba_trainer_mobile_ffi_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun ffi_dba_trainer_mobile_ffi_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_dba_trainer_mobile_ffi_rust_future_cancel_i64(`handle`: Long,
    ): Unit
    external fun ffi_dba_trainer_mobile_ffi_rust_future_free_i64(`handle`: Long,
    ): Unit
    external fun ffi_dba_trainer_mobile_ffi_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Long
    external fun ffi_dba_trainer_mobile_ffi_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_dba_trainer_mobile_ffi_rust_future_cancel_f32(`handle`: Long,
    ): Unit
    external fun ffi_dba_trainer_mobile_ffi_rust_future_free_f32(`handle`: Long,
    ): Unit
    external fun ffi_dba_trainer_mobile_ffi_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Float
    external fun ffi_dba_trainer_mobile_ffi_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_dba_trainer_mobile_ffi_rust_future_cancel_f64(`handle`: Long,
    ): Unit
    external fun ffi_dba_trainer_mobile_ffi_rust_future_free_f64(`handle`: Long,
    ): Unit
    external fun ffi_dba_trainer_mobile_ffi_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Double
    external fun ffi_dba_trainer_mobile_ffi_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_dba_trainer_mobile_ffi_rust_future_cancel_rust_buffer(`handle`: Long,
    ): Unit
    external fun ffi_dba_trainer_mobile_ffi_rust_future_free_rust_buffer(`handle`: Long,
    ): Unit
    external fun ffi_dba_trainer_mobile_ffi_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): RustBuffer.ByValue
    external fun ffi_dba_trainer_mobile_ffi_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
    ): Unit
    external fun ffi_dba_trainer_mobile_ffi_rust_future_cancel_void(`handle`: Long,
    ): Unit
    external fun ffi_dba_trainer_mobile_ffi_rust_future_free_void(`handle`: Long,
    ): Unit
    external fun ffi_dba_trainer_mobile_ffi_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
    ): Unit

        
}

private fun uniffiCheckContractApiVersion(lib: IntegrityCheckingUniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_dba_trainer_mobile_ffi_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}
@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: IntegrityCheckingUniffiLib) {
    if ((lib.uniffi_dba_trainer_mobile_ffi_checksum_func_core_version() and 0xFFFF) != 53180) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_dba_trainer_mobile_ffi_checksum_func_hello_android() and 0xFFFF) != 57456) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_dba_trainer_mobile_ffi_checksum_method_mobiletrainer_active_session() and 0xFFFF) != 5082) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_dba_trainer_mobile_ffi_checksum_method_mobiletrainer_cancel_session() and 0xFFFF) != 23547) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_dba_trainer_mobile_ffi_checksum_method_mobiletrainer_clear_statistics() and 0xFFFF) != 46729) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_dba_trainer_mobile_ffi_checksum_method_mobiletrainer_current_question() and 0xFFFF) != 42502) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_dba_trainer_mobile_ffi_checksum_method_mobiletrainer_start_all_topics_session() and 0xFFFF) != 51578) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_dba_trainer_mobile_ffi_checksum_method_mobiletrainer_start_course_session() and 0xFFFF) != 62481) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_dba_trainer_mobile_ffi_checksum_method_mobiletrainer_start_topic_session() and 0xFFFF) != 24608) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_dba_trainer_mobile_ffi_checksum_method_mobiletrainer_statistics_all() and 0xFFFF) != 10535) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_dba_trainer_mobile_ffi_checksum_method_mobiletrainer_statistics_course() and 0xFFFF) != 36506) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_dba_trainer_mobile_ffi_checksum_method_mobiletrainer_statistics_topic() and 0xFFFF) != 38875) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_dba_trainer_mobile_ffi_checksum_method_mobiletrainer_submit_answer() and 0xFFFF) != 23027) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_dba_trainer_mobile_ffi_checksum_method_mobiletrainer_topics() and 0xFFFF) != 50680) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if ((lib.uniffi_dba_trainer_mobile_ffi_checksum_constructor_mobiletrainer_new() and 0xFFFF) != 37674) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

/**
 * @suppress
 */
public fun uniffiEnsureInitialized() {
    // Call arbitrary methods on IntegrityCheckingUniffiLib and UniffiLib to ensure that
    // their init blocks run. This ensures initialization across crates works as expected.
    IntegrityCheckingUniffiLib.ensureInitialized()
    UniffiLib.ensureInitialized()
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            for (arg in args) {
                when (arg) {
                    is Disposable -> arg.destroy()
                    is ArrayList<*> -> {
                        for (idx in arg.indices) {
                            val element = arg[idx]
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Map<*, *> -> {
                        for (element in arg.values) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Iterable<*> -> {
                        for (element in arg) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                }
            }
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/** 
 * Placeholder object used to signal that we're constructing an interface with a FFI handle.
 *
 * This is the first argument for interface constructors that input a raw handle. It exists is that
 * so we can avoid signature conflicts when an interface has a regular constructor than inputs a
 * Long.
 *
 * @suppress
 * */
object UniffiWithHandle

/** 
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoHandle
/**
 * The cleaner interface for Object finalization code to run.
 * This is the entry point to any implementation that we're using.
 *
 * The cleaner registers objects and returns cleanables, so now we are
 * defining a `UniffiCleaner` with a `UniffiClenaer.Cleanable` to abstract the
 * different implmentations available at compile time.
 *
 * @suppress
 */
interface UniffiCleaner {
    interface Cleanable {
        fun clean()
    }

    fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable

    companion object
}

// The fallback Jna cleaner, which is available for both Android, and the JVM.
private class UniffiJnaCleaner : UniffiCleaner {
    private val cleaner = com.sun.jna.internal.Cleaner.getCleaner()

    override fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable =
        UniffiJnaCleanable(cleaner.register(value, cleanUpTask))
}

private class UniffiJnaCleanable(
    private val cleanable: com.sun.jna.internal.Cleaner.Cleanable,
) : UniffiCleaner.Cleanable {
    override fun clean() = cleanable.clean()
}


// We decide at uniffi binding generation time whether we were
// using Android or not.
// There are further runtime checks to chose the correct implementation
// of the cleaner.


private fun UniffiCleaner.Companion.create(): UniffiCleaner =
    if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.UPSIDE_DOWN_CAKE) {
        AndroidSystemCleaner()
    } else {
        UniffiJnaCleaner()
    }

// The SystemCleaner, available from API Level 33.
// Some API Level 33 OSes do not support using it, so we require API Level 34.
@RequiresApi(Build.VERSION_CODES.UPSIDE_DOWN_CAKE)
private class AndroidSystemCleaner : UniffiCleaner {
    val cleaner = android.system.SystemCleaner.cleaner()

    override fun register(value: Any, cleanUpTask: Runnable): UniffiCleaner.Cleanable =
        AndroidSystemCleanable(cleaner.register(value, cleanUpTask))
}

@RequiresApi(Build.VERSION_CODES.UPSIDE_DOWN_CAKE)
private class AndroidSystemCleanable(
    private val cleanable: java.lang.ref.Cleaner.Cleanable,
) : UniffiCleaner.Cleanable {
    override fun clean() = cleanable.clean()
}

/**
 * @suppress
 */
public object FfiConverterULong: FfiConverter<ULong, Long> {
    override fun lift(value: Long): ULong {
        return value.toULong()
    }

    override fun read(buf: ByteBuffer): ULong {
        return lift(buf.getLong())
    }

    override fun lower(value: ULong): Long {
        return value.toLong()
    }

    override fun allocationSize(value: ULong) = 8UL

    override fun write(value: ULong, buf: ByteBuffer) {
        buf.putLong(value.toLong())
    }
}

/**
 * @suppress
 */
public object FfiConverterLong: FfiConverter<Long, Long> {
    override fun lift(value: Long): Long {
        return value
    }

    override fun read(buf: ByteBuffer): Long {
        return buf.getLong()
    }

    override fun lower(value: Long): Long {
        return value
    }

    override fun allocationSize(value: Long) = 8UL

    override fun write(value: Long, buf: ByteBuffer) {
        buf.putLong(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterDouble: FfiConverter<Double, Double> {
    override fun lift(value: Double): Double {
        return value
    }

    override fun read(buf: ByteBuffer): Double {
        return buf.getDouble()
    }

    override fun lower(value: Double): Double {
        return value
    }

    override fun allocationSize(value: Double) = 8UL

    override fun write(value: Double, buf: ByteBuffer) {
        buf.putDouble(value)
    }
}

/**
 * @suppress
 */
public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1UL

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}


// This template implements a class for working with a Rust struct via a handle
// to the live Rust struct on the other side of the FFI.
//
// There's some subtlety here, because we have to be careful not to operate on a Rust
// struct after it has been dropped, and because we must expose a public API for freeing
// theq Kotlin wrapper object in lieu of reliable finalizers. The core requirements are:
//
//   * Each instance holds an opaque handle to the underlying Rust struct.
//     Method calls need to read this handle from the object's state and pass it in to
//     the Rust FFI.
//
//   * When an instance is no longer needed, its handle should be passed to a
//     special destructor function provided by the Rust FFI, which will drop the
//     underlying Rust struct.
//
//   * Given an instance, calling code is expected to call the special
//     `destroy` method in order to free it after use, either by calling it explicitly
//     or by using a higher-level helper like the `use` method. Failing to do so risks
//     leaking the underlying Rust struct.
//
//   * We can't assume that calling code will do the right thing, and must be prepared
//     to handle Kotlin method calls executing concurrently with or even after a call to
//     `destroy`, and to handle multiple (possibly concurrent!) calls to `destroy`.
//
//   * We must never allow Rust code to operate on the underlying Rust struct after
//     the destructor has been called, and must never call the destructor more than once.
//     Doing so may trigger memory unsafety.
//
//   * To mitigate many of the risks of leaking memory and use-after-free unsafety, a `Cleaner`
//     is implemented to call the destructor when the Kotlin object becomes unreachable.
//     This is done in a background thread. This is not a panacea, and client code should be aware that
//      1. the thread may starve if some there are objects that have poorly performing
//     `drop` methods or do significant work in their `drop` methods.
//      2. the thread is shared across the whole library. This can be tuned by using `android_cleaner = true`,
//         or `android = true` in the [`kotlin` section of the `uniffi.toml` file](https://mozilla.github.io/uniffi-rs/kotlin/configuration.html).
//
// If we try to implement this with mutual exclusion on access to the handle, there is the
// possibility of a race between a method call and a concurrent call to `destroy`:
//
//    * Thread A starts a method call, reads the value of the handle, but is interrupted
//      before it can pass the handle over the FFI to Rust.
//    * Thread B calls `destroy` and frees the underlying Rust struct.
//    * Thread A resumes, passing the already-read handle value to Rust and triggering
//      a use-after-free.
//
// One possible solution would be to use a `ReadWriteLock`, with each method call taking
// a read lock (and thus allowed to run concurrently) and the special `destroy` method
// taking a write lock (and thus blocking on live method calls). However, we aim not to
// generate methods with any hidden blocking semantics, and a `destroy` method that might
// block if called incorrectly seems to meet that bar.
//
// So, we achieve our goals by giving each instance an associated `AtomicLong` counter to track
// the number of in-flight method calls, and an `AtomicBoolean` flag to indicate whether `destroy`
// has been called. These are updated according to the following rules:
//
//    * The initial value of the counter is 1, indicating a live object with no in-flight calls.
//      The initial value for the flag is false.
//
//    * At the start of each method call, we atomically check the counter.
//      If it is 0 then the underlying Rust struct has already been destroyed and the call is aborted.
//      If it is nonzero them we atomically increment it by 1 and proceed with the method call.
//
//    * At the end of each method call, we atomically decrement and check the counter.
//      If it has reached zero then we destroy the underlying Rust struct.
//
//    * When `destroy` is called, we atomically flip the flag from false to true.
//      If the flag was already true we silently fail.
//      Otherwise we atomically decrement and check the counter.
//      If it has reached zero then we destroy the underlying Rust struct.
//
// Astute readers may observe that this all sounds very similar to the way that Rust's `Arc<T>` works,
// and indeed it is, with the addition of a flag to guard against multiple calls to `destroy`.
//
// The overall effect is that the underlying Rust struct is destroyed only when `destroy` has been
// called *and* all in-flight method calls have completed, avoiding violating any of the expectations
// of the underlying Rust code.
//
// This makes a cleaner a better alternative to _not_ calling `destroy()` as
// and when the object is finished with, but the abstraction is not perfect: if the Rust object's `drop`
// method is slow, and/or there are many objects to cleanup, and it's on a low end Android device, then the cleaner
// thread may be starved, and the app will leak memory.
//
// In this case, `destroy`ing manually may be a better solution.
//
// The cleaner can live side by side with the manual calling of `destroy`. In the order of responsiveness, uniffi objects
// with Rust peers are reclaimed:
//
// 1. By calling the `destroy` method of the object, which calls `rustObject.free()`. If that doesn't happen:
// 2. When the object becomes unreachable, AND the Cleaner thread gets to call `rustObject.free()`. If the thread is starved then:
// 3. The memory is reclaimed when the process terminates.
//
// [1] https://stackoverflow.com/questions/24376768/can-java-finalize-an-object-when-it-is-still-in-scope/24380219
//


public interface MobileTrainerInterface {
    
    fun `activeSession`(): MobileSessionProgress?
    
    fun `cancelSession`(`sessionId`: kotlin.Long)
    
    fun `clearStatistics`()
    
    fun `currentQuestion`(`sessionId`: kotlin.Long): MobileQuestion?
    
    fun `startAllTopicsSession`(`limit`: MobileQuestionLimit): MobileQuizSession
    
    fun `startCourseSession`(`courseCode`: kotlin.String, `limit`: MobileQuestionLimit): MobileQuizSession
    
    fun `startTopicSession`(`topicId`: kotlin.Long, `limit`: MobileQuestionLimit): MobileQuizSession
    
    fun `statisticsAll`(`limit`: MobileStatisticsLimit): MobileTrainingStats
    
    fun `statisticsCourse`(`courseCode`: kotlin.String, `limit`: MobileStatisticsLimit): MobileTrainingStats
    
    fun `statisticsTopic`(`topicId`: kotlin.Long, `limit`: MobileStatisticsLimit): MobileTrainingStats
    
    fun `submitAnswer`(`sessionId`: kotlin.Long, `questionId`: kotlin.Long, `answerOptionIds`: List<kotlin.Long>): MobileAnswerResult
    
    fun `topics`(): List<MobileTopic>
    
    companion object
}

open class MobileTrainer: Disposable, AutoCloseable, MobileTrainerInterface
{

    @Suppress("UNUSED_PARAMETER")
    /**
     * @suppress
     */
    constructor(withHandle: UniffiWithHandle, handle: Long) {
        this.handle = handle
        this.cleanable = UniffiLib.CLEANER.register(this, UniffiCleanAction(handle))
    }

    /**
     * @suppress
     *
     * This constructor can be used to instantiate a fake object. Only used for tests. Any
     * attempt to actually use an object constructed this way will fail as there is no
     * connected Rust object.
     */
    @Suppress("UNUSED_PARAMETER")
    constructor(noHandle: NoHandle) {
        this.handle = 0
        this.cleanable = null
    }
    constructor(`databasePath`: kotlin.String) :
        this(UniffiWithHandle, 
    uniffiRustCallWithError(MobileException) { _status ->
    UniffiLib.uniffi_dba_trainer_mobile_ffi_fn_constructor_mobiletrainer_new(
    
        
        FfiConverterString.lower(`databasePath`),_status)
}
    )

    protected val handle: Long
    protected val cleanable: UniffiCleaner.Cleanable?

    private val wasDestroyed = AtomicBoolean(false)
    private val callCounter = AtomicLong(1)

    /**
     * Whether the current object has been destroyed and its reference is gone in the Rust side.
     */
    val uniffiIsDestroyed: Boolean get() = wasDestroyed.get()

    override fun destroy() {
        // Only allow a single call to this method.
        // TODO: maybe we should log a warning if called more than once?
        if (this.wasDestroyed.compareAndSet(false, true)) {
            // This decrement always matches the initial count of 1 given at creation time.
            if (this.callCounter.decrementAndGet() == 0L) {
                cleanable?.clean()
            }
        }
    }

    @Synchronized
    override fun close() {
        this.destroy()
    }

    internal inline fun <R> callWithHandle(block: (handle: Long) -> R): R {
        // Check and increment the call counter, to keep the object alive.
        // This needs a compare-and-set retry loop in case of concurrent updates.
        do {
            val c = this.callCounter.get()
            if (c == 0L) {
                throw IllegalStateException("${this.javaClass.simpleName} object has already been destroyed")
            }
            if (c == Long.MAX_VALUE) {
                throw IllegalStateException("${this.javaClass.simpleName} call counter would overflow")
            }
        } while (! this.callCounter.compareAndSet(c, c + 1L))
        // Now we can safely do the method call without the handle being freed concurrently.
        try {
            return block(this.uniffiCloneHandle())
        } finally {
            // This decrement always matches the increment we performed above.
            if (this.callCounter.decrementAndGet() == 0L) {
                cleanable?.clean()
            }
        }
    }

    // Use a static inner class instead of a closure so as not to accidentally
    // capture `this` as part of the cleanable's action.
    private class UniffiCleanAction(private val handle: Long) : Runnable {
        override fun run() {
            if (handle == 0.toLong()) {
                // Fake object created with `NoHandle`, don't try to free.
                return;
            }
            uniffiRustCall { status ->
                UniffiLib.uniffi_dba_trainer_mobile_ffi_fn_free_mobiletrainer(handle, status)
            }
        }
    }

    /**
     * @suppress
     */
    fun uniffiCloneHandle(): Long {
        if (handle == 0.toLong()) {
            throw InternalException("uniffiCloneHandle() called on NoHandle object");
        }
        return uniffiRustCall() { status ->
            UniffiLib.uniffi_dba_trainer_mobile_ffi_fn_clone_mobiletrainer(handle, status)
        }
    }

    
    @Throws(MobileException::class)override fun `activeSession`(): MobileSessionProgress? {
            return FfiConverterOptionalTypeMobileSessionProgress.lift(
    callWithHandle {
    uniffiRustCallWithError(MobileException) { _status ->
    UniffiLib.uniffi_dba_trainer_mobile_ffi_fn_method_mobiletrainer_active_session(
        it,
        _status)
}
    }
    )
    }
    

    
    @Throws(MobileException::class)override fun `cancelSession`(`sessionId`: kotlin.Long)
        = 
    callWithHandle {
    uniffiRustCallWithError(MobileException) { _status ->
    UniffiLib.uniffi_dba_trainer_mobile_ffi_fn_method_mobiletrainer_cancel_session(
        it,
        
        FfiConverterLong.lower(`sessionId`),_status)
}
    }
    
    

    
    @Throws(MobileException::class)override fun `clearStatistics`()
        = 
    callWithHandle {
    uniffiRustCallWithError(MobileException) { _status ->
    UniffiLib.uniffi_dba_trainer_mobile_ffi_fn_method_mobiletrainer_clear_statistics(
        it,
        _status)
}
    }
    
    

    
    @Throws(MobileException::class)override fun `currentQuestion`(`sessionId`: kotlin.Long): MobileQuestion? {
            return FfiConverterOptionalTypeMobileQuestion.lift(
    callWithHandle {
    uniffiRustCallWithError(MobileException) { _status ->
    UniffiLib.uniffi_dba_trainer_mobile_ffi_fn_method_mobiletrainer_current_question(
        it,
        
        FfiConverterLong.lower(`sessionId`),_status)
}
    }
    )
    }
    

    
    @Throws(MobileException::class)override fun `startAllTopicsSession`(`limit`: MobileQuestionLimit): MobileQuizSession {
            return FfiConverterTypeMobileQuizSession.lift(
    callWithHandle {
    uniffiRustCallWithError(MobileException) { _status ->
    UniffiLib.uniffi_dba_trainer_mobile_ffi_fn_method_mobiletrainer_start_all_topics_session(
        it,
        
        FfiConverterTypeMobileQuestionLimit.lower(`limit`),_status)
}
    }
    )
    }
    

    
    @Throws(MobileException::class)override fun `startCourseSession`(`courseCode`: kotlin.String, `limit`: MobileQuestionLimit): MobileQuizSession {
            return FfiConverterTypeMobileQuizSession.lift(
    callWithHandle {
    uniffiRustCallWithError(MobileException) { _status ->
    UniffiLib.uniffi_dba_trainer_mobile_ffi_fn_method_mobiletrainer_start_course_session(
        it,
        
        FfiConverterString.lower(`courseCode`),
        FfiConverterTypeMobileQuestionLimit.lower(`limit`),_status)
}
    }
    )
    }
    

    
    @Throws(MobileException::class)override fun `startTopicSession`(`topicId`: kotlin.Long, `limit`: MobileQuestionLimit): MobileQuizSession {
            return FfiConverterTypeMobileQuizSession.lift(
    callWithHandle {
    uniffiRustCallWithError(MobileException) { _status ->
    UniffiLib.uniffi_dba_trainer_mobile_ffi_fn_method_mobiletrainer_start_topic_session(
        it,
        
        FfiConverterLong.lower(`topicId`),
        FfiConverterTypeMobileQuestionLimit.lower(`limit`),_status)
}
    }
    )
    }
    

    
    @Throws(MobileException::class)override fun `statisticsAll`(`limit`: MobileStatisticsLimit): MobileTrainingStats {
            return FfiConverterTypeMobileTrainingStats.lift(
    callWithHandle {
    uniffiRustCallWithError(MobileException) { _status ->
    UniffiLib.uniffi_dba_trainer_mobile_ffi_fn_method_mobiletrainer_statistics_all(
        it,
        
        FfiConverterTypeMobileStatisticsLimit.lower(`limit`),_status)
}
    }
    )
    }
    

    
    @Throws(MobileException::class)override fun `statisticsCourse`(`courseCode`: kotlin.String, `limit`: MobileStatisticsLimit): MobileTrainingStats {
            return FfiConverterTypeMobileTrainingStats.lift(
    callWithHandle {
    uniffiRustCallWithError(MobileException) { _status ->
    UniffiLib.uniffi_dba_trainer_mobile_ffi_fn_method_mobiletrainer_statistics_course(
        it,
        
        FfiConverterString.lower(`courseCode`),
        FfiConverterTypeMobileStatisticsLimit.lower(`limit`),_status)
}
    }
    )
    }
    

    
    @Throws(MobileException::class)override fun `statisticsTopic`(`topicId`: kotlin.Long, `limit`: MobileStatisticsLimit): MobileTrainingStats {
            return FfiConverterTypeMobileTrainingStats.lift(
    callWithHandle {
    uniffiRustCallWithError(MobileException) { _status ->
    UniffiLib.uniffi_dba_trainer_mobile_ffi_fn_method_mobiletrainer_statistics_topic(
        it,
        
        FfiConverterLong.lower(`topicId`),
        FfiConverterTypeMobileStatisticsLimit.lower(`limit`),_status)
}
    }
    )
    }
    

    
    @Throws(MobileException::class)override fun `submitAnswer`(`sessionId`: kotlin.Long, `questionId`: kotlin.Long, `answerOptionIds`: List<kotlin.Long>): MobileAnswerResult {
            return FfiConverterTypeMobileAnswerResult.lift(
    callWithHandle {
    uniffiRustCallWithError(MobileException) { _status ->
    UniffiLib.uniffi_dba_trainer_mobile_ffi_fn_method_mobiletrainer_submit_answer(
        it,
        
        FfiConverterLong.lower(`sessionId`),
        FfiConverterLong.lower(`questionId`),
        FfiConverterSequenceLong.lower(`answerOptionIds`),_status)
}
    }
    )
    }
    

    
    @Throws(MobileException::class)override fun `topics`(): List<MobileTopic> {
            return FfiConverterSequenceTypeMobileTopic.lift(
    callWithHandle {
    uniffiRustCallWithError(MobileException) { _status ->
    UniffiLib.uniffi_dba_trainer_mobile_ffi_fn_method_mobiletrainer_topics(
        it,
        _status)
}
    }
    )
    }
    

    

    


    
    
    /**
     * @suppress
     */
    companion object
    
}


/**
 * @suppress
 */
public object FfiConverterTypeMobileTrainer: FfiConverter<MobileTrainer, Long> {
    override fun lower(value: MobileTrainer): Long {
        return value.uniffiCloneHandle()
    }

    override fun lift(value: Long): MobileTrainer {
        return MobileTrainer(UniffiWithHandle, value)
    }

    override fun read(buf: ByteBuffer): MobileTrainer {
        return lift(buf.getLong())
    }

    override fun allocationSize(value: MobileTrainer) = 8UL

    override fun write(value: MobileTrainer, buf: ByteBuffer) {
        buf.putLong(lower(value))
    }
}



data class MobileAnswerOption (
    val `id`: kotlin.Long
    , 
    val `text`: kotlin.String
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeMobileAnswerOption: FfiConverterRustBuffer<MobileAnswerOption> {
    override fun read(buf: ByteBuffer): MobileAnswerOption {
        return MobileAnswerOption(
            FfiConverterLong.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: MobileAnswerOption) = (
            FfiConverterLong.allocationSize(value.`id`) +
            FfiConverterString.allocationSize(value.`text`)
    )

    override fun write(value: MobileAnswerOption, buf: ByteBuffer) {
            FfiConverterLong.write(value.`id`, buf)
            FfiConverterString.write(value.`text`, buf)
    }
}



data class MobileAnswerResult (
    val `questionId`: kotlin.Long
    , 
    val `selectedOptionIds`: List<kotlin.Long>
    , 
    val `correctOptionIds`: List<kotlin.Long>
    , 
    val `isCorrect`: kotlin.Boolean
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeMobileAnswerResult: FfiConverterRustBuffer<MobileAnswerResult> {
    override fun read(buf: ByteBuffer): MobileAnswerResult {
        return MobileAnswerResult(
            FfiConverterLong.read(buf),
            FfiConverterSequenceLong.read(buf),
            FfiConverterSequenceLong.read(buf),
            FfiConverterBoolean.read(buf),
        )
    }

    override fun allocationSize(value: MobileAnswerResult) = (
            FfiConverterLong.allocationSize(value.`questionId`) +
            FfiConverterSequenceLong.allocationSize(value.`selectedOptionIds`) +
            FfiConverterSequenceLong.allocationSize(value.`correctOptionIds`) +
            FfiConverterBoolean.allocationSize(value.`isCorrect`)
    )

    override fun write(value: MobileAnswerResult, buf: ByteBuffer) {
            FfiConverterLong.write(value.`questionId`, buf)
            FfiConverterSequenceLong.write(value.`selectedOptionIds`, buf)
            FfiConverterSequenceLong.write(value.`correctOptionIds`, buf)
            FfiConverterBoolean.write(value.`isCorrect`, buf)
    }
}



data class MobileQuestion (
    val `id`: kotlin.Long
    , 
    val `topicId`: kotlin.Long
    , 
    val `questionType`: MobileQuestionType
    , 
    val `text`: kotlin.String
    , 
    val `explanation`: kotlin.String
    , 
    val `source`: MobileSource
    , 
    val `options`: List<MobileAnswerOption>
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeMobileQuestion: FfiConverterRustBuffer<MobileQuestion> {
    override fun read(buf: ByteBuffer): MobileQuestion {
        return MobileQuestion(
            FfiConverterLong.read(buf),
            FfiConverterLong.read(buf),
            FfiConverterTypeMobileQuestionType.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterTypeMobileSource.read(buf),
            FfiConverterSequenceTypeMobileAnswerOption.read(buf),
        )
    }

    override fun allocationSize(value: MobileQuestion) = (
            FfiConverterLong.allocationSize(value.`id`) +
            FfiConverterLong.allocationSize(value.`topicId`) +
            FfiConverterTypeMobileQuestionType.allocationSize(value.`questionType`) +
            FfiConverterString.allocationSize(value.`text`) +
            FfiConverterString.allocationSize(value.`explanation`) +
            FfiConverterTypeMobileSource.allocationSize(value.`source`) +
            FfiConverterSequenceTypeMobileAnswerOption.allocationSize(value.`options`)
    )

    override fun write(value: MobileQuestion, buf: ByteBuffer) {
            FfiConverterLong.write(value.`id`, buf)
            FfiConverterLong.write(value.`topicId`, buf)
            FfiConverterTypeMobileQuestionType.write(value.`questionType`, buf)
            FfiConverterString.write(value.`text`, buf)
            FfiConverterString.write(value.`explanation`, buf)
            FfiConverterTypeMobileSource.write(value.`source`, buf)
            FfiConverterSequenceTypeMobileAnswerOption.write(value.`options`, buf)
    }
}



data class MobileQuizSession (
    val `id`: kotlin.Long
    , 
    val `currentIndex`: kotlin.ULong
    , 
    val `totalQuestions`: kotlin.ULong
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeMobileQuizSession: FfiConverterRustBuffer<MobileQuizSession> {
    override fun read(buf: ByteBuffer): MobileQuizSession {
        return MobileQuizSession(
            FfiConverterLong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
        )
    }

    override fun allocationSize(value: MobileQuizSession) = (
            FfiConverterLong.allocationSize(value.`id`) +
            FfiConverterULong.allocationSize(value.`currentIndex`) +
            FfiConverterULong.allocationSize(value.`totalQuestions`)
    )

    override fun write(value: MobileQuizSession, buf: ByteBuffer) {
            FfiConverterLong.write(value.`id`, buf)
            FfiConverterULong.write(value.`currentIndex`, buf)
            FfiConverterULong.write(value.`totalQuestions`, buf)
    }
}



data class MobileSessionProgress (
    val `id`: kotlin.Long
    , 
    val `topicId`: kotlin.Long?
    , 
    val `courseCode`: kotlin.String?
    , 
    val `currentIndex`: kotlin.ULong
    , 
    val `totalQuestions`: kotlin.ULong
    , 
    val `answeredQuestions`: kotlin.ULong
    , 
    val `correctAnswers`: kotlin.ULong
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeMobileSessionProgress: FfiConverterRustBuffer<MobileSessionProgress> {
    override fun read(buf: ByteBuffer): MobileSessionProgress {
        return MobileSessionProgress(
            FfiConverterLong.read(buf),
            FfiConverterOptionalLong.read(buf),
            FfiConverterOptionalString.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
        )
    }

    override fun allocationSize(value: MobileSessionProgress) = (
            FfiConverterLong.allocationSize(value.`id`) +
            FfiConverterOptionalLong.allocationSize(value.`topicId`) +
            FfiConverterOptionalString.allocationSize(value.`courseCode`) +
            FfiConverterULong.allocationSize(value.`currentIndex`) +
            FfiConverterULong.allocationSize(value.`totalQuestions`) +
            FfiConverterULong.allocationSize(value.`answeredQuestions`) +
            FfiConverterULong.allocationSize(value.`correctAnswers`)
    )

    override fun write(value: MobileSessionProgress, buf: ByteBuffer) {
            FfiConverterLong.write(value.`id`, buf)
            FfiConverterOptionalLong.write(value.`topicId`, buf)
            FfiConverterOptionalString.write(value.`courseCode`, buf)
            FfiConverterULong.write(value.`currentIndex`, buf)
            FfiConverterULong.write(value.`totalQuestions`, buf)
            FfiConverterULong.write(value.`answeredQuestions`, buf)
            FfiConverterULong.write(value.`correctAnswers`, buf)
    }
}



data class MobileSource (
    val `kind`: MobileSourceKind
    , 
    val `module`: kotlin.String
    , 
    val `section`: kotlin.String
    , 
    val `locator`: kotlin.String
    , 
    val `url`: kotlin.String?
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeMobileSource: FfiConverterRustBuffer<MobileSource> {
    override fun read(buf: ByteBuffer): MobileSource {
        return MobileSource(
            FfiConverterTypeMobileSourceKind.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterOptionalString.read(buf),
        )
    }

    override fun allocationSize(value: MobileSource) = (
            FfiConverterTypeMobileSourceKind.allocationSize(value.`kind`) +
            FfiConverterString.allocationSize(value.`module`) +
            FfiConverterString.allocationSize(value.`section`) +
            FfiConverterString.allocationSize(value.`locator`) +
            FfiConverterOptionalString.allocationSize(value.`url`)
    )

    override fun write(value: MobileSource, buf: ByteBuffer) {
            FfiConverterTypeMobileSourceKind.write(value.`kind`, buf)
            FfiConverterString.write(value.`module`, buf)
            FfiConverterString.write(value.`section`, buf)
            FfiConverterString.write(value.`locator`, buf)
            FfiConverterOptionalString.write(value.`url`, buf)
    }
}



data class MobileTopic (
    val `id`: kotlin.Long
    , 
    val `courseCode`: kotlin.String
    , 
    val `slug`: kotlin.String
    , 
    val `title`: kotlin.String
    , 
    val `description`: kotlin.String?
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeMobileTopic: FfiConverterRustBuffer<MobileTopic> {
    override fun read(buf: ByteBuffer): MobileTopic {
        return MobileTopic(
            FfiConverterLong.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterOptionalString.read(buf),
        )
    }

    override fun allocationSize(value: MobileTopic) = (
            FfiConverterLong.allocationSize(value.`id`) +
            FfiConverterString.allocationSize(value.`courseCode`) +
            FfiConverterString.allocationSize(value.`slug`) +
            FfiConverterString.allocationSize(value.`title`) +
            FfiConverterOptionalString.allocationSize(value.`description`)
    )

    override fun write(value: MobileTopic, buf: ByteBuffer) {
            FfiConverterLong.write(value.`id`, buf)
            FfiConverterString.write(value.`courseCode`, buf)
            FfiConverterString.write(value.`slug`, buf)
            FfiConverterString.write(value.`title`, buf)
            FfiConverterOptionalString.write(value.`description`, buf)
    }
}



data class MobileTrainingStats (
    val `completedSessions`: kotlin.ULong
    , 
    val `cancelledSessions`: kotlin.ULong
    , 
    val `answeredQuestions`: kotlin.ULong
    , 
    val `correctAnswers`: kotlin.ULong
    , 
    val `incorrectAnswers`: kotlin.ULong
    , 
    val `accuracyPercent`: kotlin.Double
    
){
    

    

    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeMobileTrainingStats: FfiConverterRustBuffer<MobileTrainingStats> {
    override fun read(buf: ByteBuffer): MobileTrainingStats {
        return MobileTrainingStats(
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterDouble.read(buf),
        )
    }

    override fun allocationSize(value: MobileTrainingStats) = (
            FfiConverterULong.allocationSize(value.`completedSessions`) +
            FfiConverterULong.allocationSize(value.`cancelledSessions`) +
            FfiConverterULong.allocationSize(value.`answeredQuestions`) +
            FfiConverterULong.allocationSize(value.`correctAnswers`) +
            FfiConverterULong.allocationSize(value.`incorrectAnswers`) +
            FfiConverterDouble.allocationSize(value.`accuracyPercent`)
    )

    override fun write(value: MobileTrainingStats, buf: ByteBuffer) {
            FfiConverterULong.write(value.`completedSessions`, buf)
            FfiConverterULong.write(value.`cancelledSessions`, buf)
            FfiConverterULong.write(value.`answeredQuestions`, buf)
            FfiConverterULong.write(value.`correctAnswers`, buf)
            FfiConverterULong.write(value.`incorrectAnswers`, buf)
            FfiConverterDouble.write(value.`accuracyPercent`, buf)
    }
}





sealed class MobileException: kotlin.Exception() {
    
    class Core(
        
        val v1: kotlin.String
        ) : MobileException() {
        override val message
            get() = "v1=${ v1 }"
    }
    

    


    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<MobileException> {
        override fun lift(error_buf: RustBuffer.ByValue): MobileException = FfiConverterTypeMobileError.lift(error_buf)
    }

    
}

/**
 * @suppress
 */
public object FfiConverterTypeMobileError : FfiConverterRustBuffer<MobileException> {
    override fun read(buf: ByteBuffer): MobileException {
        

        return when(buf.getInt()) {
            1 -> MobileException.Core(
                FfiConverterString.read(buf),
                )
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: MobileException): ULong {
        return when(value) {
            is MobileException.Core -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.v1)
            )
        }
    }

    override fun write(value: MobileException, buf: ByteBuffer) {
        when(value) {
            is MobileException.Core -> {
                buf.putInt(1)
                FfiConverterString.write(value.v1, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}




enum class MobileQuestionLimit {
    
    TWENTY,
    FIFTY,
    ALL;

    


    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeMobileQuestionLimit: FfiConverterRustBuffer<MobileQuestionLimit> {
    override fun read(buf: ByteBuffer) = try {
        MobileQuestionLimit.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: MobileQuestionLimit) = 4UL

    override fun write(value: MobileQuestionLimit, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






enum class MobileQuestionType {
    
    SINGLE_CHOICE,
    MULTIPLE_CHOICE;

    


    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeMobileQuestionType: FfiConverterRustBuffer<MobileQuestionType> {
    override fun read(buf: ByteBuffer) = try {
        MobileQuestionType.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: MobileQuestionType) = 4UL

    override fun write(value: MobileQuestionType, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






enum class MobileSourceKind {
    
    COURSE_MATERIAL,
    POSTGRE_SQL_DOCS;

    


    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeMobileSourceKind: FfiConverterRustBuffer<MobileSourceKind> {
    override fun read(buf: ByteBuffer) = try {
        MobileSourceKind.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: MobileSourceKind) = 4UL

    override fun write(value: MobileSourceKind, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






enum class MobileStatisticsLimit {
    
    ANY,
    TWENTY,
    FIFTY,
    ALL_QUESTIONS;

    


    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeMobileStatisticsLimit: FfiConverterRustBuffer<MobileStatisticsLimit> {
    override fun read(buf: ByteBuffer) = try {
        MobileStatisticsLimit.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: MobileStatisticsLimit) = 4UL

    override fun write(value: MobileStatisticsLimit, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}






/**
 * @suppress
 */
public object FfiConverterOptionalLong: FfiConverterRustBuffer<kotlin.Long?> {
    override fun read(buf: ByteBuffer): kotlin.Long? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterLong.read(buf)
    }

    override fun allocationSize(value: kotlin.Long?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterLong.allocationSize(value)
        }
    }

    override fun write(value: kotlin.Long?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterLong.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalString: FfiConverterRustBuffer<kotlin.String?> {
    override fun read(buf: ByteBuffer): kotlin.String? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterString.read(buf)
    }

    override fun allocationSize(value: kotlin.String?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterString.allocationSize(value)
        }
    }

    override fun write(value: kotlin.String?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterString.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeMobileQuestion: FfiConverterRustBuffer<MobileQuestion?> {
    override fun read(buf: ByteBuffer): MobileQuestion? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeMobileQuestion.read(buf)
    }

    override fun allocationSize(value: MobileQuestion?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeMobileQuestion.allocationSize(value)
        }
    }

    override fun write(value: MobileQuestion?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeMobileQuestion.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterOptionalTypeMobileSessionProgress: FfiConverterRustBuffer<MobileSessionProgress?> {
    override fun read(buf: ByteBuffer): MobileSessionProgress? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterTypeMobileSessionProgress.read(buf)
    }

    override fun allocationSize(value: MobileSessionProgress?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterTypeMobileSessionProgress.allocationSize(value)
        }
    }

    override fun write(value: MobileSessionProgress?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterTypeMobileSessionProgress.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceLong: FfiConverterRustBuffer<List<kotlin.Long>> {
    override fun read(buf: ByteBuffer): List<kotlin.Long> {
        val len = buf.getInt()
        return List<kotlin.Long>(len) {
            FfiConverterLong.read(buf)
        }
    }

    override fun allocationSize(value: List<kotlin.Long>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterLong.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<kotlin.Long>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterLong.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeMobileAnswerOption: FfiConverterRustBuffer<List<MobileAnswerOption>> {
    override fun read(buf: ByteBuffer): List<MobileAnswerOption> {
        val len = buf.getInt()
        return List<MobileAnswerOption>(len) {
            FfiConverterTypeMobileAnswerOption.read(buf)
        }
    }

    override fun allocationSize(value: List<MobileAnswerOption>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeMobileAnswerOption.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<MobileAnswerOption>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeMobileAnswerOption.write(it, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeMobileTopic: FfiConverterRustBuffer<List<MobileTopic>> {
    override fun read(buf: ByteBuffer): List<MobileTopic> {
        val len = buf.getInt()
        return List<MobileTopic>(len) {
            FfiConverterTypeMobileTopic.read(buf)
        }
    }

    override fun allocationSize(value: List<MobileTopic>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeMobileTopic.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<MobileTopic>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeMobileTopic.write(it, buf)
        }
    }
} fun `coreVersion`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_dba_trainer_mobile_ffi_fn_func_core_version(
    
        _status)
}
    )
    }
    
 fun `helloAndroid`(): kotlin.String {
            return FfiConverterString.lift(
    uniffiRustCall() { _status ->
    UniffiLib.uniffi_dba_trainer_mobile_ffi_fn_func_hello_android(
    
        _status)
}
    )
    }
    


